POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjYyODczNzI0NzkwYTk4Mjc2ZTViNDdkYSIsImlhdCI6MTY1MzAyOTk2NH0.UemM4Q1ePcqPwmBWr0JsPFQDdg_i47DKxRqcYvWhV7o

{
    "title": "fdhdfh",
    "author": "fdh",
    "url": "DGjhdgj",
    "likes": "236"
}